### ISSUE TITLE
pip install doesn't automatically install 'requests' dependency

### ISSUE THREAD

**Issue by eripa** [karanlyons/chump#4]
In a clean virtualenv:

```
$ pip install chump
Downloading/unpacking chump
  Downloading chump-1.3.1.tar.gz
  Running setup.py egg_info for package chump
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "/home/pi/.virtualenvs/gpio/build/chump/setup.py", line 5, in <module>
        import chump
      File "./chump/__init__.py", line 11, in <module>
        import requests
    ImportError: No module named 'requests'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "/home/pi/.virtualenvs/gpio/build/chump/setup.py", line 5, in <module>

    import chump

  File "./chump/__init__.py", line 11, in <module>

    import requests

ImportError: No module named 'requests'
```

But installing requests manually first did seem to solve the issue, however the following error occurs during installation of requests 1.2.3 (Using Python 3.3.2).

```
$ pip install requests==1.2.3
Downloading/unpacking requests==1.2.3
  Downloading requests-1.2.3.tar.gz (348kB): 348kB downloaded
  Running setup.py egg_info for package requests

Installing collected packages: requests
  Running setup.py install for requests

      File "/home/pi/.virtualenvs/gpio/lib/python3.3/site-packages/requests/packages/urllib3/contrib/ntlmpool.py", line 38
        """
         ^
    SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 130-131: truncated \uXXXX escape

Successfully installed requests
```

It does however seem to work fine, but maybe it's time to change the requests version to a newer one? Such as 2.x.x

**Comment by karanlyons** [comment]
Note that as of 1.5 requests is not longer a dependency *at all*, in either Py2 or Py3.
